version: '3.4'

services:
  bookstore:
    container_name: 'bookstore'
    build:
      context: .
      dockerfile: BookStore/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - sqlserver
  sqlserver:
    container_name: 'sqlserver'
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "MyDbSecretPassword123"
      ACCEPT_EULA: "Y"
